services:
  postgres:
    restart: always
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - DEBUG=false
      - POSTGRES_USER=robbo
      - POSTGRES_PASSWORD=robbo_pwd
      - POSTGRES_DB=robbo_db
    volumes:
      - postgres_data:/usr/lib/postgresql

volumes:
  postgres_data: {}